language: r
cache:
  packages: true
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./_deploy.sh; else echo "PR so not deploying"; fi
warnings_are_errors: false
addons:
  apt:
      packages:
            - gdal-bin
            - libgdal1-dev
            - libproj-dev
            - libudunits2-dev
            - libprotobuf-dev
            - protobuf-compiler
            - libv8-dev
            - libjq-dev
            - libgeos-dev
            - libprotoc-dev
            - libnetcdf-dev
            
install: 
  - R -e "install.packages('sf')"
  - R -e "install.packages('tmap')"
  - R -e "install.packages('rmapshaper')"
  - R -e "install.packages('bookdown')"
  - R -e "install.packages('dplyr')"
  - R -e "install.packages('janitor')"
  - R -e "install.packages('fs')"
  - R -e "install.packages('knitr')"
  - R -e "install.packages('kableExtra')"
  - R -e "install.packages('DT')"
  - R -e "install.packages('DBI')"
  - R -e "install.packages('dbplyr')"
  - R -e "install.packages('haven')"
  - R -e "install.packages('bigrquery')"
  - R -e "install.packages('openxlsx')"
  - R -e "install.packages('xltabr')"
  - R -e "install.packages('readr')"
  - R -e "install.packages('reshape2')"
  - R -e "install.packages('tidyr')"
  - R -e "install.packages('lubridate')"
